config/routes.rb
Rails.application.routes.draw do
  
  root to: 'books#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :loans, only: [:index] do
    member do
      post '/checkin', to: 'loans#checkin'
    end
  end
  resources :copies, only: [:index, :show]
  resources :books, except: [:destroy] do
    member do
      post '/checkout', to: 'books#checkout'
      post '/add_copy', to: 'books#add_copy'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :copies

  validates :title, presence: true

  def available_copies
    copies.where(available: true)
  end

  def available?
    available_copies.count > 0
  end

  def add_copy
    copies.create
  end

  def checkout_by(user)
    return false unless self.available?
      
    copy = available_copies.first
    copy.checkout_by(user)
  end
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :book
  has_many :loans

  def book_title
    book.title
  end

  def book_author
    book.author
  end

  def book_genre
    book.genre
  end

  def book_sub_genre
    book.sub_genre
  end

  def book_num_of_pages
    book.num_of_pages
  end

  def book_publisher
    book.publisher
  end

  def available?
    self.available
  end

  def checkout_by(user)
    return false unless self.available?

    loans.create(
      user_id: user.id,
      checkout_date: Date.today,
      due_date: 1.week.from_now.to_date
    )
    self.update(available: false)
  end

  def current_loan
    loans.where(
        'checkout_date IS NOT NULL AND checkin_date IS NULL'
      ).first
  end

  def borrower 
    current_loan.try(:user)
  end

  def checkin
    return false if self.available?

    current_loan.update(checkin_date: Date.today)
    self.update(available: true)
  end
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :copy

  validates :checkout_date, :due_date, presence: true

  def book_title
    copy.book.title
  end

  def book_author
    copy.book.author
  end

  def book_genre
    copy.book.genre
  end

  def book_sub_genre
    copy.book.sub_genre
  end

  def book_num_of_pages
    copy.book.num_of_pages
  end

  def book_publisher
    copy.book.publisher
  end

  def checkin
    copy.checkin
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :loans

  has_secure_password

  validates :email, presence: true,
    uniqueness: true,
    format: {
      with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
      message: "invalid format"
    }

  def admin?
    self.admin
  end
  
  def current_loans
    loans.where('checkout_date IS NOT NULL AND checkin_date IS NULL')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user
    @current_user
  end

  helper_method :logged_in?, :current_user

  private
  def require_login
    unless logged_in?
      redirect_to login_url, alert: 'You must be logged in to access this section!'
    end
  end

  def require_admin
    unless @current_user.admin?
      redirect_to root_url, alert: 'You must be admin user to access this section!'
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: [:index]
  before_action :require_admin, except: [:index, :checkout]
  def index
    @books = Book.paginate(:page => params[:page])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'It has been created successfully!'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to books_url, notice: 'It has been updated successfully!'
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def checkout
    book = Book.find(params[:id])
    if book.checkout_by(@current_user)
      redirect_to books_url, notice: 'It has been borrowed successfully!'
    else
      redirect_to books_url, alert: 'It is not available to borrow now!'
    end
  end

  def add_copy
    book = Book.find(params[:id])
    book.add_copy
    redirect_to book, notice: 'One copy has been added successfully!'
  end

  private
  def book_params
    params.require(:book).permit(
        :title, :author, :genre, :sub_genre,
        :num_of_pages, :publisher
      )
  end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :require_admin
  def index
    @copies = Copy.paginate(:page => params[:page])
  end

  def show
    @copy = Copy.find(params[:id])
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
    @current_loans = @current_user.current_loans
  end

  def checkin
    loan = Loan.find(params[:id])
    if loan.checkin
      redirect_to loans_url, notice: 'It has been returned successfully!'
    else
      redirect_to loans_url, alert: 'It cannot be returned now!'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :sub_genre %><br />
    <%= f.text_field :sub_genre %>
  </div>
  <div class="field">
    <%= f.label :num_of_pages %><br />
    <%= f.number_field :num_of_pages %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="actions"><%= f.submit "Update" %></div>
<% end %>

app/views/books/index.html.erb
<h1>All books</h1>
<% if logged_in? && current_user.admin? %>
  <%= link_to 'Create new book', new_book_path %>
<% end %>
<% @books.each do |book| %>
  <p>
    Title: <%= book.title %> 
    <% if logged_in? && book.available? %>
      | <%= link_to 'Borrow', checkout_book_path(book), method: :post %>
    <% end %>
  </p>
  <p>Author: <%= book.author %></p>
  <p>Genre: <%= book.genre %></p>
  <p>Sub genre: <%= book.sub_genre %></p>
  <p>Number of pages: <%= book.num_of_pages %></p>
  <p>Publisher: <%= book.publisher %></p>
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Copy details', book %> | <%= link_to 'Edit', edit_book_path(book) %>
  <% end %>
  <hr>
<% end %>
<%= will_paginate @books %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :sub_genre %><br />
    <%= f.text_field :sub_genre %>
  </div>
  <div class="field">
    <%= f.label :num_of_pages %><br />
    <%= f.number_field :num_of_pages %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="actions"><%= f.submit "Create" %></div>
<% end %>

app/views/books/show.html.erb
<h1>All copies for <%= @book.title %></h1>
<%= link_to 'Add copy', add_copy_book_path(@book), method: :post %>
<% @book.copies.each do |copy| %>
  <p>Status: <%= copy.available? ? 'Currently in the library' : 'Currently checkout' %></p>
  <p>Borrower: <%= copy.borrower.try(:email) %></p>
  <hr>
<% end %>

app/views/copies/index.html.erb
<h1>All copies</h1>
<% @copies.each do |copy| %>
  <p>Title: <%= copy.book_title %></p>
  <p>Author: <%= copy.book_author %></p>
  <p>Genre: <%= copy.book_genre %></p>
  <p>Status: <%= copy.available? ? 'Currently in the library' : 'Currently checkout' %></p>
  <%= link_to 'Borrow history', copy %>
  <hr>
<% end %>
<%= will_paginate @copies %>

app/views/copies/show.html.erb
<h1>Borrow history for <%= @copy.book_title %></h1>
<% @copy.loans.each do |loan| %>
  <p>Checkout date: <%= loan.checkout_date %></p>
  <p>Checkin date: <%= loan.checkin_date %></p>
  <p>Due date: <%= loan.due_date %></p>
  <p>Borrower email: <%= loan.user.email %></p>
  <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_header">
      <% if logged_in? && current_user.admin? %>
        <%= current_user.email %> | <%= link_to 'All books', books_path %> | <%= link_to 'All copies', copies_path %> | <%= link_to 'My books', loans_path %> | <%= link_to 'Logout', logout_path %>
      <% elsif logged_in? %>
        <%= current_user.email %> | <%= link_to 'All books', books_path %> | <%= link_to 'My books', loans_path %> | <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= link_to 'All books', books_path %> | <%= link_to "Sign Up", signup_path %> | <%= link_to "Log In", login_path %>
      <% end %>
    </div>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/loans/index.html.erb
<h1>My books</h1>
<% @current_loans.each do |loan| %>
  <p>Title: <%= loan.book_title %> | <%= link_to 'Return', checkin_loan_path(loan), method: :post %></p>
  <p>Author: <%= loan.book_author %></p>
  <p>Genre: <%= loan.book_genre %></p>
  <p>Due date: <%= loan.due_date %></p>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>